package com.turboocelots.oasis.models;
/**
 * Created by Tiffany on 2/25/17.
 * A instance of a Report
 */

public class Report {

    protected String reportNumber;
    protected  String dateTime;
    protected String reporterName;
    protected ConditionOfWater waterCondition;
    protected TypeOfWater waterType;



    /**
     * Creates an instance of a report
     * @param reportNumber generated by syste,
     * @param dateTime date and time report was created

     * @param reporterName the name of the reporter
     * @param waterCondition condition of the water
     * @param waterType type of water
     */
    public Report(String reportNumber,String dateTime,String reporterName,
                  ConditionOfWater waterCondition, TypeOfWater waterType){
        this.reportNumber = reportNumber;
        this.dateTime = dateTime;
        this.reporterName = reporterName;
        this.waterCondition = waterCondition;
        this.waterType = waterType;
    }




}
