package com.turboocelots.oasis.models;
/**
 * Created by Tiffany on 2/25/17.
 * A instance of a Report
 */

public class Report {

    protected String reportNumber;
    protected  String dateTime;
    protected String reporterName;
    protected ConditionOfWater waterCondition;
    protected TypeOfWater waterType;



    /**
     * Creates an instance of a report
     * @param reportNumber generated by syste,
     * @param dateTime date and time report was created

     * @param reporterName the name of the reporter
     * @param waterCondition condition of the water
     * @param waterType type of water
     */
    public Report(String reportNumber,String dateTime,String reporterName,
                  ConditionOfWater waterCondition, TypeOfWater waterType){
        this.reportNumber = reportNumber;
        this.dateTime = dateTime;
        this.reporterName = reporterName;
        this.waterCondition = waterCondition;
        this.waterType = waterType;
    }

    public String getReportNumber() { return reportNumber; }
    public void setReportNumber(String reportNumber) { this.reportNumber = reportNumber; }

    public String getDateTime() { return dateTime; }
    public void setDateTime(String dateTime) { this.dateTime = dateTime; }

    public String getReporterName() { return reporterName; }
    public void setReporterName(String reporterName) { this.reporterName = reporterName; }

    public ConditionOfWater getWaterCondition() { return waterCondition; }
    public void setWaterCondition(ConditionOfWater waterCondition) { this.waterCondition = waterCondition; }

    public TypeOfWater getWaterType() { return waterType; }
    public void setWaterType(TypeOfWater waterType) { this.waterType = waterType;}
}
