package com.turboocelots.oasis.models;
/**
 * Created by Tiffany on 2/25/17.
 * A instance of a Report
 */

public class Report {

    protected String reportNumber;
    protected  String dateTime;
    protected String reporterName;
    protected  double reportLat;
    protected double reportLong;
    protected ConditionOfWater waterCondition;
    protected TypeOfWater waterType;



    /**
     * Creates an instance of a report
     * @param reportNumber generated by syste,
     * @param dateTime date and time report was created
     * @param reportLat  latitude of water source
     * @param reportLong longitude of water source
     * @param reporterName the name of the reporter
     * @param waterCondition condition of the water
     * @param waterType type of water
     */
    public Report(String reportNumber,String dateTime,String reporterName,double reportLat, double reportLong,
                  ConditionOfWater waterCondition, TypeOfWater waterType){
        this.reportNumber = reportNumber;
        this.dateTime = dateTime;
        this.reporterName = reporterName;
        this.reportLat = reportLat;
        this.reportLong = reportLong;
        this.waterCondition = waterCondition;
        this.waterType = waterType;
    }

    /**
     * get report number
     * @return String representation of reportNumber
     */
    public String getReportNumber() { return reportNumber; }

    /**
     * get report date and time
     * @return String representation of date and time
     */
    public String getDateTime() { return dateTime; }

    /**
     * get reporter name
     * @return String representation of reporter name
     */
    public String getReporterName() { return reporterName; }

    /**
     * get report lat
     * @return double in lat
     */
    public double getReportLat() { return reportLat; }

    /**
     * get report long
     * @return double in long
     */
    public double getReportLong() {return reportLong;}

    /**
     * get condition water
     * @return condition of water
     */
    public ConditionOfWater getWaterCondition() { return waterCondition; }

    /**
     * get water type
     * @return water type
     */
    public TypeOfWater getWaterType() { return waterType; }


    @Override
    public String toString() {
        return getReportNumber() + "  " + "Lat: " +
                Double.toString(getReportLat()) + " Long: " +
                Double.toString(getReportLong()) + "  " + "Type of Water:" + "  " +
                getWaterType().toString() + "  " + "Water Condition: " +
                getWaterCondition();
    }
}
