package com.turboocelots.oasis.models;

import java.sql.Timestamp;
import java.util.Calendar;

/**
 * Created by Tiffany on 3/7/17.
 */

public class WaterQualityReport extends Report {
    private OverallCondition oCondition;
    private String virusPPM;
    private String contaminantsPPM;

    /**
     * Creates an instance of a report
     * @param reportNumber generated by system,
     * @param dateTime a Timestamp class that references the day it was created
     * @param reportLat  latitude of water source
     * @param reportLong longitude of water source
     * @param reporterName the name of the reporter
     * @param oCondition condition of water
     * @param contaminantsPPM measurement of water quality
     * @param virusPPM measurement of water quality
     */
    public WaterQualityReport(String reportNumber, Timestamp dateTime, String reporterName,
                              double reportLat, double reportLong,
                              OverallCondition oCondition, String virusPPM, String contaminantsPPM){
        super(reportNumber,dateTime,reporterName,reportLat,reportLong);
        this.oCondition = oCondition;
        this.virusPPM = virusPPM;
        this.contaminantsPPM =contaminantsPPM;
    }

    public OverallCondition getoCondition() {
        return oCondition;
    }

    public void setoCondition(OverallCondition oCondition) {
        this.oCondition = oCondition;
    }

    public String getVirusPPM() {
        return virusPPM;
    }

    public void setVirusPPM(String virusPPM) {
        this.virusPPM = virusPPM;
    }

    public String getContaminantsPPM() {
        return contaminantsPPM;
    }

    public void setContaminantsPPM(String contaminantsPPM) {
        this.contaminantsPPM = contaminantsPPM;
    }

    @Override
    public String toString(){
        return   "Water Quality Report: \n "+reporterName + "\n" + dateTime +"\n" + reportNumber + "\n" +
                "Latitude: " + reportLat + "\n" + "Longitude: " + reportLong + "\n"
                + "Overall Condition:" + oCondition.toString() + "\n" +
                " Virus PPM: "  +virusPPM+ "\n" +  " Contaminants PPM: "  + contaminantsPPM;

    }




}
