package com.turboocelots.oasis.models;

import com.turboocelots.oasis.models.constants.ConditionOfWater;
import com.turboocelots.oasis.models.constants.TypeOfWater;

import java.sql.Timestamp;

/**
 * Created by Tiffany on 2/25/17.
 * A instance of a WaterSourceReport
 */

public class WaterSourceReport extends Report {


    private ConditionOfWater waterCondition;
    private TypeOfWater waterType;

    /**
     * Creates an instance of a report
     * @param reportNumber generated by system,
     * @param dateTime date and time report was created
     * @param reportLat  latitude of water source
     * @param reportLong longitude of water source
     * @param reporterName the name of the reporter
     * @param waterCondition condition of the water
     * @param waterType type of water
     */
    public WaterSourceReport(String reportNumber, Timestamp dateTime, String reporterName,
                             double reportLat, double reportLong,
                             ConditionOfWater waterCondition, TypeOfWater waterType) {
        super(reportNumber,dateTime,reporterName,reportLat,reportLong);
        this.waterCondition = waterCondition;
        this.waterType = waterType;
    }


    /**
     * Gets the water condition
     * @return the current water condition
     */
    public ConditionOfWater getWaterCondition() { return waterCondition; }

    /**
     * Sets the water condition
     * @param waterCondition the new water condition to set
     */
    public void setWaterCondition(ConditionOfWater waterCondition) {
        this.waterCondition = waterCondition; }

    /**
     * Gets the water type
     * @return the water type
     */
    public TypeOfWater getWaterType() { return waterType; }

    /**
     * Sets the water type
     * @param waterType the new WaterType
     */
    public void setWaterType(TypeOfWater waterType) { this.waterType = waterType;}


    /**
     * Returns a ReportLocation representation of this object
     * @return ReportLocation representing this object
     */
    public ReportLocation getReportLocation() {
        return new ReportLocation(this);
    }

    @Override
    public String getTitle() {
        return this.getDateTime() + " " + this.getWaterCondition() + " " + this.getWaterType();
    }

    @Override
    public String getDescription() {
        return this.getReporterName() + "\n" + this.getDateTime() + "\n" + "Water Type: "
                + this.getWaterType() + "\n" +
                "Water Condition: " +  this.getWaterCondition() + "\n"
                + this.getReportNumber();
    }


    @Override
    public String toString() {
        return "Water Source Report: \n" + this.getReporterName() + "\n" + this.getDateTime()
                +"\n" + this.getReportNumber() + "\n" +
                "Latitude: " + this.getReportLat() + "\n" + "Longitude: " + this.getReportLong()
                + "\n"
                + "Water Condition:" + waterCondition.toString() + "\n" +
                  " Water Type: "  + waterType.toString();
    }
}
